name: Run Docker Compose

on:
  push:
    branches:
      - master

jobs:
  run-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path:
           -'!README.md'
           -'!.github/**'
           -'**'
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Set up Docker Compose
        run: docker-compose --version

      - name: Start Services with Docker Compose
        run: docker-compose up -d

      - name: Wait for Web App to Start
        run: |
          # Wait for the web app to be ready
          while ! curl -s http://localhost:8080; do
            sleep 5
          done

      - name: Test Web App
        run: curl -s http://localhost:8080
      # Add any additional steps for testing or validation as needed

      - name: Clean Up
        run: docker-compose down
