name: CI workflow

on:
  push:
    branches:
      - master

jobs:
  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # with:
        #   path:
        #     -'!README.md'
        #     -'!.github/**'
        #     -'**'

    # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
  
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
  
      # - name: Build and Compile
      #   run: |
      #      npm install
      #      npm run build
  
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2


  run-docker-compose:
    name: Run Docker Compose
    runs-on: ubuntu-latest
    needs: codeql-analysis

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        # with:
        #   path:
        #     -'!README.md'
        #     -'!.github/**'
        #     -'**'
           
      - name: Set up Docker Compose
        run: docker-compose --version

      - name: Start Services with Docker Compose
        run: docker-compose up -d

      - name: Wait for Web App to Start
        run: |
          # Wait for the web app to be ready
          while ! curl -s http://localhost:8080; do
            sleep 5
          done

      - name: Test Web App
        run: curl -s http://localhost:8080
      # Add any additional steps for testing or validation as needed

      - name: Clean Up
        run: docker-compose down
      
